export interface ProblemRowData {
  globalNum: number;
  patternNum: number;
  title: string;
  lcNumber: number;
  difficulty: "Easy" | "Medium" | "Hard";
}

export interface PatternSectionData {
  id: number;
  numStr: string;
  name: string;
  count: number;
  startGlobal: number;
  endGlobal: number;
  problems: ProblemRowData[];
}

export const PATTERNS_DATA: PatternSectionData[] = [
  {
    id: 1,
    numStr: "01",
    name: "Arrays & Hashing",
    count: 18,
    startGlobal: 1,
    endGlobal: 18,
    problems: [
      { globalNum: 1, patternNum: 1, title: "Contains Duplicate", lcNumber: 217, difficulty: "Easy" },
      { globalNum: 2, patternNum: 2, title: "Valid Anagram", lcNumber: 242, difficulty: "Easy" },
      { globalNum: 3, patternNum: 3, title: "Two Sum", lcNumber: 1, difficulty: "Easy" },
      { globalNum: 4, patternNum: 4, title: "Pascal's Triangle", lcNumber: 118, difficulty: "Easy" },
      { globalNum: 5, patternNum: 5, title: "Majority Element", lcNumber: 169, difficulty: "Easy" },
      { globalNum: 6, patternNum: 6, title: "Group Anagrams", lcNumber: 49, difficulty: "Medium" },
      { globalNum: 7, patternNum: 7, title: "Top K Frequent Elements", lcNumber: 347, difficulty: "Medium" },
      { globalNum: 8, patternNum: 8, title: "Product of Array Except Self", lcNumber: 238, difficulty: "Medium" },
      { globalNum: 9, patternNum: 9, title: "Valid Sudoku", lcNumber: 36, difficulty: "Medium" },
      { globalNum: 10, patternNum: 10, title: "Longest Consecutive Sequence", lcNumber: 128, difficulty: "Medium" },
      { globalNum: 11, patternNum: 11, title: "Sort Colors", lcNumber: 75, difficulty: "Medium" },
      { globalNum: 12, patternNum: 12, title: "Next Permutation", lcNumber: 31, difficulty: "Medium" },
      { globalNum: 13, patternNum: 13, title: "Set Matrix Zeroes", lcNumber: 73, difficulty: "Medium" },
      { globalNum: 14, patternNum: 14, title: "Rotate Image", lcNumber: 48, difficulty: "Medium" },
      { globalNum: 15, patternNum: 15, title: "Spiral Matrix", lcNumber: 54, difficulty: "Medium" },
      { globalNum: 16, patternNum: 16, title: "Subarray Sum Equals K", lcNumber: 560, difficulty: "Medium" },
      { globalNum: 17, patternNum: 17, title: "Encode and Decode Strings", lcNumber: 271, difficulty: "Medium" },
      { globalNum: 18, patternNum: 18, title: "First Missing Positive", lcNumber: 41, difficulty: "Hard" },
    ],
  },
  {
    id: 2,
    numStr: "02",
    name: "Two Pointers",
    count: 12,
    startGlobal: 19,
    endGlobal: 30,
    problems: [
      { globalNum: 19, patternNum: 1, title: "Valid Palindrome", lcNumber: 125, difficulty: "Easy" },
      { globalNum: 20, patternNum: 2, title: "Move Zeroes", lcNumber: 283, difficulty: "Easy" },
      { globalNum: 21, patternNum: 3, title: "Remove Duplicates", lcNumber: 26, difficulty: "Easy" },
      { globalNum: 22, patternNum: 4, title: "Squares of Sorted Array", lcNumber: 977, difficulty: "Easy" },
      { globalNum: 23, patternNum: 5, title: "Merge Sorted Array", lcNumber: 88, difficulty: "Easy" },
      { globalNum: 24, patternNum: 6, title: "Two Sum II", lcNumber: 167, difficulty: "Medium" },
      { globalNum: 25, patternNum: 7, title: "3Sum", lcNumber: 15, difficulty: "Medium" },
      { globalNum: 26, patternNum: 8, title: "Container With Most Water", lcNumber: 11, difficulty: "Medium" },
      { globalNum: 27, patternNum: 9, title: "3Sum Closest", lcNumber: 16, difficulty: "Medium" },
      { globalNum: 28, patternNum: 10, title: "4Sum", lcNumber: 18, difficulty: "Medium" },
      { globalNum: 29, patternNum: 11, title: "Boats to Save People", lcNumber: 881, difficulty: "Medium" },
      { globalNum: 30, patternNum: 12, title: "Trapping Rain Water", lcNumber: 42, difficulty: "Hard" },
    ],
  },
  {
    id: 3,
    numStr: "03",
    name: "Sliding Window",
    count: 10,
    startGlobal: 31,
    endGlobal: 40,
    problems: [
      { globalNum: 31, patternNum: 1, title: "Best Time to Buy & Sell Stock", lcNumber: 121, difficulty: "Easy" },
      { globalNum: 32, patternNum: 2, title: "Maximum Average Subarray I", lcNumber: 643, difficulty: "Easy" },
      { globalNum: 33, patternNum: 3, title: "Longest Substring Without Repeating", lcNumber: 3, difficulty: "Medium" },
      { globalNum: 34, patternNum: 4, title: "Longest Repeating Character Replace", lcNumber: 424, difficulty: "Medium" },
      { globalNum: 35, patternNum: 5, title: "Permutation in String", lcNumber: 567, difficulty: "Medium" },
      { globalNum: 36, patternNum: 6, title: "Max Consecutive Ones III", lcNumber: 1004, difficulty: "Medium" },
      { globalNum: 37, patternNum: 7, title: "Minimum Size Subarray Sum", lcNumber: 209, difficulty: "Medium" },
      { globalNum: 38, patternNum: 8, title: "Fruit Into Baskets", lcNumber: 904, difficulty: "Medium" },
      { globalNum: 39, patternNum: 9, title: "Minimum Window Substring", lcNumber: 76, difficulty: "Hard" },
      { globalNum: 40, patternNum: 10, title: "Sliding Window Maximum", lcNumber: 239, difficulty: "Hard" },
    ],
  },
  {
    id: 4,
    numStr: "04",
    name: "Stack",
    count: 11,
    startGlobal: 41,
    endGlobal: 51,
    problems: [
      { globalNum: 41, patternNum: 1, title: "Valid Parentheses", lcNumber: 20, difficulty: "Easy" },
      { globalNum: 42, patternNum: 2, title: "Next Greater Element I", lcNumber: 496, difficulty: "Easy" },
      { globalNum: 43, patternNum: 3, title: "Min Stack", lcNumber: 155, difficulty: "Medium" },
      { globalNum: 44, patternNum: 4, title: "Evaluate Reverse Polish Notation", lcNumber: 150, difficulty: "Medium" },
      { globalNum: 45, patternNum: 5, title: "Generate Parentheses", lcNumber: 22, difficulty: "Medium" },
      { globalNum: 46, patternNum: 6, title: "Daily Temperatures", lcNumber: 739, difficulty: "Medium" },
      { globalNum: 47, patternNum: 7, title: "Car Fleet", lcNumber: 853, difficulty: "Medium" },
      { globalNum: 48, patternNum: 8, title: "Online Stock Span", lcNumber: 901, difficulty: "Medium" },
      { globalNum: 49, patternNum: 9, title: "Asteroid Collision", lcNumber: 735, difficulty: "Medium" },
      { globalNum: 50, patternNum: 10, title: "Simplify Path", lcNumber: 71, difficulty: "Medium" },
      { globalNum: 51, patternNum: 11, title: "Largest Rectangle in Histogram", lcNumber: 84, difficulty: "Hard" },
    ],
  },
  {
    id: 5,
    numStr: "05",
    name: "Binary Search",
    count: 12,
    startGlobal: 52,
    endGlobal: 63,
    problems: [
      { globalNum: 52, patternNum: 1, title: "Binary Search", lcNumber: 704, difficulty: "Easy" },
      { globalNum: 53, patternNum: 2, title: "Search Insert Position", lcNumber: 35, difficulty: "Easy" },
      { globalNum: 54, patternNum: 3, title: "First Bad Version", lcNumber: 278, difficulty: "Easy" },
      { globalNum: 55, patternNum: 4, title: "Search a 2D Matrix", lcNumber: 74, difficulty: "Medium" },
      { globalNum: 56, patternNum: 5, title: "Koko Eating Bananas", lcNumber: 875, difficulty: "Medium" },
      { globalNum: 57, patternNum: 6, title: "Find Minimum in Rotated Array", lcNumber: 153, difficulty: "Medium" },
      { globalNum: 58, patternNum: 7, title: "Search in Rotated Sorted Array", lcNumber: 33, difficulty: "Medium" },
      { globalNum: 59, patternNum: 8, title: "Time Based Key-Value Store", lcNumber: 981, difficulty: "Medium" },
      { globalNum: 60, patternNum: 9, title: "Find Peak Element", lcNumber: 162, difficulty: "Medium" },
      { globalNum: 61, patternNum: 10, title: "Capacity To Ship Packages", lcNumber: 1011, difficulty: "Medium" },
      { globalNum: 62, patternNum: 11, title: "Split Array Largest Sum", lcNumber: 410, difficulty: "Hard" },
      { globalNum: 63, patternNum: 12, title: "Median of Two Sorted Arrays", lcNumber: 4, difficulty: "Hard" },
    ],
  },
  {
    id: 6,
    numStr: "06",
    name: "Linked List",
    count: 13,
    startGlobal: 64,
    endGlobal: 76,
    problems: [
      { globalNum: 64, patternNum: 1, title: "Reverse Linked List", lcNumber: 206, difficulty: "Easy" },
      { globalNum: 65, patternNum: 2, title: "Merge Two Sorted Lists", lcNumber: 21, difficulty: "Easy" },
      { globalNum: 66, patternNum: 3, title: "Linked List Cycle", lcNumber: 141, difficulty: "Easy" },
      { globalNum: 67, patternNum: 4, title: "Middle of the Linked List", lcNumber: 876, difficulty: "Easy" },
      { globalNum: 68, patternNum: 5, title: "Palindrome Linked List", lcNumber: 234, difficulty: "Easy" },
      { globalNum: 69, patternNum: 6, title: "Reorder List", lcNumber: 143, difficulty: "Medium" },
      { globalNum: 70, patternNum: 7, title: "Remove Nth Node From End", lcNumber: 19, difficulty: "Medium" },
      { globalNum: 71, patternNum: 8, title: "Copy List with Random Pointer", lcNumber: 138, difficulty: "Medium" },
      { globalNum: 72, patternNum: 9, title: "Add Two Numbers", lcNumber: 2, difficulty: "Medium" },
      { globalNum: 73, patternNum: 10, title: "LRU Cache", lcNumber: 146, difficulty: "Medium" },
      { globalNum: 74, patternNum: 11, title: "Swap Nodes in Pairs", lcNumber: 24, difficulty: "Medium" },
      { globalNum: 75, patternNum: 12, title: "Merge k Sorted Lists", lcNumber: 23, difficulty: "Hard" },
      { globalNum: 76, patternNum: 13, title: "Reverse Nodes in k-Group", lcNumber: 25, difficulty: "Hard" },
    ],
  },
  {
    id: 7,
    numStr: "07",
    name: "Trees",
    count: 22,
    startGlobal: 77,
    endGlobal: 98,
    problems: [
      { globalNum: 77, patternNum: 1, title: "Invert Binary Tree", lcNumber: 226, difficulty: "Easy" },
      { globalNum: 78, patternNum: 2, title: "Maximum Depth of Binary Tree", lcNumber: 104, difficulty: "Easy" },
      { globalNum: 79, patternNum: 3, title: "Diameter of Binary Tree", lcNumber: 543, difficulty: "Easy" },
      { globalNum: 80, patternNum: 4, title: "Balanced Binary Tree", lcNumber: 110, difficulty: "Easy" },
      { globalNum: 81, patternNum: 5, title: "Same Tree", lcNumber: 100, difficulty: "Easy" },
      { globalNum: 82, patternNum: 6, title: "Subtree of Another Tree", lcNumber: 572, difficulty: "Easy" },
      { globalNum: 83, patternNum: 7, title: "LCA of BST", lcNumber: 235, difficulty: "Easy" },
      { globalNum: 84, patternNum: 8, title: "Level Order Traversal", lcNumber: 102, difficulty: "Medium" },
      { globalNum: 85, patternNum: 9, title: "Right Side View", lcNumber: 199, difficulty: "Medium" },
      { globalNum: 86, patternNum: 10, title: "Count Good Nodes", lcNumber: 1448, difficulty: "Medium" },
      { globalNum: 87, patternNum: 11, title: "Validate BST", lcNumber: 98, difficulty: "Medium" },
      { globalNum: 88, patternNum: 12, title: "Kth Smallest in BST", lcNumber: 230, difficulty: "Medium" },
      { globalNum: 89, patternNum: 13, title: "Construct Tree from Pre/In", lcNumber: 105, difficulty: "Medium" },
      { globalNum: 90, patternNum: 14, title: "LCA of Binary Tree", lcNumber: 236, difficulty: "Medium" },
      { globalNum: 91, patternNum: 15, title: "Flatten Binary Tree", lcNumber: 114, difficulty: "Medium" },
      { globalNum: 92, patternNum: 16, title: "Path Sum II", lcNumber: 113, difficulty: "Medium" },
      { globalNum: 93, patternNum: 17, title: "Populating Next Right Pointers", lcNumber: 116, difficulty: "Medium" },
      { globalNum: 94, patternNum: 18, title: "All Nodes Distance K", lcNumber: 863, difficulty: "Medium" },
      { globalNum: 95, patternNum: 19, title: "Zigzag Level Order", lcNumber: 103, difficulty: "Medium" },
      { globalNum: 96, patternNum: 20, title: "Binary Tree Maximum Path Sum", lcNumber: 124, difficulty: "Hard" },
      { globalNum: 97, patternNum: 21, title: "Serialize and Deserialize Tree", lcNumber: 297, difficulty: "Hard" },
      { globalNum: 98, patternNum: 22, title: "Vertical Order Traversal", lcNumber: 987, difficulty: "Hard" },
    ],
  },
  {
    id: 8,
    numStr: "08",
    name: "Tries",
    count: 6,
    startGlobal: 99,
    endGlobal: 104,
    problems: [
      { globalNum: 99, patternNum: 1, title: "Implement Trie", lcNumber: 208, difficulty: "Medium" },
      { globalNum: 100, patternNum: 2, title: "Design Add & Search Words", lcNumber: 211, difficulty: "Medium" },
      { globalNum: 101, patternNum: 3, title: "Word Search II", lcNumber: 212, difficulty: "Hard" },
      { globalNum: 102, patternNum: 4, title: "Replace Words", lcNumber: 648, difficulty: "Medium" },
      { globalNum: 103, patternNum: 5, title: "Maximum XOR of Two Numbers", lcNumber: 421, difficulty: "Medium" },
      { globalNum: 104, patternNum: 6, title: "Word Break II", lcNumber: 140, difficulty: "Hard" },
    ],
  },
  {
    id: 9,
    numStr: "09",
    name: "Heap / Priority Queue",
    count: 10,
    startGlobal: 105,
    endGlobal: 114,
    problems: [
      { globalNum: 105, patternNum: 1, title: "Kth Largest Element in a Stream", lcNumber: 703, difficulty: "Easy" },
      { globalNum: 106, patternNum: 2, title: "Last Stone Weight", lcNumber: 1046, difficulty: "Easy" },
      { globalNum: 107, patternNum: 3, title: "K Closest Points to Origin", lcNumber: 973, difficulty: "Medium" },
      { globalNum: 108, patternNum: 4, title: "Kth Largest Element in an Array", lcNumber: 215, difficulty: "Medium" },
      { globalNum: 109, patternNum: 5, title: "Task Scheduler", lcNumber: 621, difficulty: "Medium" },
      { globalNum: 110, patternNum: 6, title: "Design Twitter", lcNumber: 355, difficulty: "Medium" },
      { globalNum: 111, patternNum: 7, title: "Reorganize String", lcNumber: 767, difficulty: "Medium" },
      { globalNum: 112, patternNum: 8, title: "Find K Pairs with Smallest Sums", lcNumber: 373, difficulty: "Medium" },
      { globalNum: 113, patternNum: 9, title: "Find Median from Data Stream", lcNumber: 295, difficulty: "Hard" },
      { globalNum: 114, patternNum: 10, title: "IPO", lcNumber: 502, difficulty: "Hard" },
    ],
  },
  {
    id: 10,
    numStr: "10",
    name: "Intervals",
    count: 8,
    startGlobal: 115,
    endGlobal: 122,
    problems: [
      { globalNum: 115, patternNum: 1, title: "Meeting Rooms", lcNumber: 252, difficulty: "Easy" },
      { globalNum: 116, patternNum: 2, title: "Insert Interval", lcNumber: 57, difficulty: "Medium" },
      { globalNum: 117, patternNum: 3, title: "Merge Intervals", lcNumber: 56, difficulty: "Medium" },
      { globalNum: 118, patternNum: 4, title: "Non-overlapping Intervals", lcNumber: 435, difficulty: "Medium" },
      { globalNum: 119, patternNum: 5, title: "Meeting Rooms II", lcNumber: 253, difficulty: "Medium" },
      { globalNum: 120, patternNum: 6, title: "Minimum Arrows to Burst Balloons", lcNumber: 452, difficulty: "Medium" },
      { globalNum: 121, patternNum: 7, title: "Interval List Intersections", lcNumber: 986, difficulty: "Medium" },
      { globalNum: 122, patternNum: 8, title: "Employee Free Time", lcNumber: 759, difficulty: "Hard" },
    ],
  },
  {
    id: 11,
    numStr: "11",
    name: "Greedy",
    count: 12,
    startGlobal: 123,
    endGlobal: 134,
    problems: [
      { globalNum: 123, patternNum: 1, title: "Assign Cookies", lcNumber: 455, difficulty: "Easy" },
      { globalNum: 124, patternNum: 2, title: "Maximum Subarray", lcNumber: 53, difficulty: "Medium" },
      { globalNum: 125, patternNum: 3, title: "Jump Game", lcNumber: 55, difficulty: "Medium" },
      { globalNum: 126, patternNum: 4, title: "Jump Game II", lcNumber: 45, difficulty: "Medium" },
      { globalNum: 127, patternNum: 5, title: "Gas Station", lcNumber: 134, difficulty: "Medium" },
      { globalNum: 128, patternNum: 6, title: "Hand of Straights", lcNumber: 846, difficulty: "Medium" },
      { globalNum: 129, patternNum: 7, title: "Partition Labels", lcNumber: 763, difficulty: "Medium" },
      { globalNum: 130, patternNum: 8, title: "Valid Parenthesis String", lcNumber: 678, difficulty: "Medium" },
      { globalNum: 131, patternNum: 9, title: "Candy", lcNumber: 135, difficulty: "Hard" },
      { globalNum: 132, patternNum: 10, title: "Queue Reconstruction by Height", lcNumber: 406, difficulty: "Medium" },
      { globalNum: 133, patternNum: 11, title: "Dota2 Senate", lcNumber: 649, difficulty: "Medium" },
      { globalNum: 134, patternNum: 12, title: "Maximum Swap", lcNumber: 670, difficulty: "Medium" },
    ],
  },
  {
    id: 12,
    numStr: "12",
    name: "Backtracking",
    count: 12,
    startGlobal: 135,
    endGlobal: 146,
    problems: [
      { globalNum: 135, patternNum: 1, title: "Subsets", lcNumber: 78, difficulty: "Medium" },
      { globalNum: 136, patternNum: 2, title: "Combination Sum", lcNumber: 39, difficulty: "Medium" },
      { globalNum: 137, patternNum: 3, title: "Permutations", lcNumber: 46, difficulty: "Medium" },
      { globalNum: 138, patternNum: 4, title: "Subsets II", lcNumber: 90, difficulty: "Medium" },
      { globalNum: 139, patternNum: 5, title: "Combination Sum II", lcNumber: 40, difficulty: "Medium" },
      { globalNum: 140, patternNum: 6, title: "Word Search", lcNumber: 79, difficulty: "Medium" },
      { globalNum: 141, patternNum: 7, title: "Palindrome Partitioning", lcNumber: 131, difficulty: "Medium" },
      { globalNum: 142, patternNum: 8, title: "Letter Combinations of a Phone", lcNumber: 17, difficulty: "Medium" },
      { globalNum: 143, patternNum: 9, title: "N-Queens", lcNumber: 51, difficulty: "Hard" },
      { globalNum: 144, patternNum: 10, title: "Sudoku Solver", lcNumber: 37, difficulty: "Hard" },
      { globalNum: 145, patternNum: 11, title: "Restore IP Addresses", lcNumber: 93, difficulty: "Medium" },
      { globalNum: 146, patternNum: 12, title: "Generate Parentheses", lcNumber: 22, difficulty: "Medium" },
    ],
  },
  {
    id: 13,
    numStr: "13",
    name: "Graphs",
    count: 20,
    startGlobal: 147,
    endGlobal: 166,
    problems: [
      { globalNum: 147, patternNum: 1, title: "Number of Islands", lcNumber: 200, difficulty: "Medium" },
      { globalNum: 148, patternNum: 2, title: "Max Area of Island", lcNumber: 695, difficulty: "Medium" },
      { globalNum: 149, patternNum: 3, title: "Clone Graph", lcNumber: 133, difficulty: "Medium" },
      { globalNum: 150, patternNum: 4, title: "Walls and Gates", lcNumber: 286, difficulty: "Medium" },
      { globalNum: 151, patternNum: 5, title: "Rotting Oranges", lcNumber: 994, difficulty: "Medium" },
      { globalNum: 152, patternNum: 6, title: "Pacific Atlantic Water Flow", lcNumber: 417, difficulty: "Medium" },
      { globalNum: 153, patternNum: 7, title: "Surrounded Regions", lcNumber: 130, difficulty: "Medium" },
      { globalNum: 154, patternNum: 8, title: "Course Schedule", lcNumber: 207, difficulty: "Medium" },
      { globalNum: 155, patternNum: 9, title: "Course Schedule II", lcNumber: 210, difficulty: "Medium" },
      { globalNum: 156, patternNum: 10, title: "Graph Valid Tree", lcNumber: 261, difficulty: "Medium" },
      { globalNum: 157, patternNum: 11, title: "Number of Connected Components", lcNumber: 323, difficulty: "Medium" },
      { globalNum: 158, patternNum: 12, title: "Redundant Connection", lcNumber: 684, difficulty: "Medium" },
      { globalNum: 159, patternNum: 13, title: "Word Ladder", lcNumber: 127, difficulty: "Hard" },
      { globalNum: 160, patternNum: 14, title: "Alien Dictionary", lcNumber: 269, difficulty: "Hard" },
      { globalNum: 161, patternNum: 15, title: "Is Graph Bipartite?", lcNumber: 785, difficulty: "Medium" },
      { globalNum: 162, patternNum: 16, title: "Minimum Knight Moves", lcNumber: 1197, difficulty: "Medium" },
      { globalNum: 163, patternNum: 17, title: "Shortest Path in Binary Matrix", lcNumber: 1091, difficulty: "Medium" },
      { globalNum: 164, patternNum: 18, title: "Accounts Merge", lcNumber: 721, difficulty: "Medium" },
      { globalNum: 165, patternNum: 19, title: "Cheapest Flights Within K Stops", lcNumber: 787, difficulty: "Medium" },
      { globalNum: 166, patternNum: 20, title: "Reconstruct Itinerary", lcNumber: 332, difficulty: "Hard" },
    ],
  },
  {
    id: 14,
    numStr: "14",
    name: "Advanced Graphs",
    count: 8,
    startGlobal: 167,
    endGlobal: 174,
    problems: [
      { globalNum: 167, patternNum: 1, title: "Network Delay Time", lcNumber: 743, difficulty: "Medium" },
      { globalNum: 168, patternNum: 2, title: "Swim in Rising Water", lcNumber: 778, difficulty: "Hard" },
      { globalNum: 169, patternNum: 3, title: "Min Cost to Connect All Points", lcNumber: 1584, difficulty: "Medium" },
      { globalNum: 170, patternNum: 4, title: "Path with Minimum Effort", lcNumber: 1631, difficulty: "Medium" },
      { globalNum: 171, patternNum: 5, title: "Critical Connections in a Network", lcNumber: 1192, difficulty: "Hard" },
      { globalNum: 172, patternNum: 6, title: "Bus Routes", lcNumber: 815, difficulty: "Hard" },
      { globalNum: 173, patternNum: 7, title: "Word Ladder II", lcNumber: 126, difficulty: "Hard" },
      { globalNum: 174, patternNum: 8, title: "Shortest Path Visiting All Nodes", lcNumber: 847, difficulty: "Hard" },
    ],
  },
  {
    id: 15,
    numStr: "15",
    name: "1-D Dynamic Programming",
    count: 15,
    startGlobal: 175,
    endGlobal: 189,
    problems: [
      { globalNum: 175, patternNum: 1, title: "Climbing Stairs", lcNumber: 70, difficulty: "Easy" },
      { globalNum: 176, patternNum: 2, title: "Min Cost Climbing Stairs", lcNumber: 746, difficulty: "Easy" },
      { globalNum: 177, patternNum: 3, title: "House Robber", lcNumber: 198, difficulty: "Medium" },
      { globalNum: 178, patternNum: 4, title: "House Robber II", lcNumber: 213, difficulty: "Medium" },
      { globalNum: 179, patternNum: 5, title: "Longest Palindromic Substring", lcNumber: 5, difficulty: "Medium" },
      { globalNum: 180, patternNum: 6, title: "Palindromic Substrings", lcNumber: 647, difficulty: "Medium" },
      { globalNum: 181, patternNum: 7, title: "Decode Ways", lcNumber: 91, difficulty: "Medium" },
      { globalNum: 182, patternNum: 8, title: "Coin Change", lcNumber: 322, difficulty: "Medium" },
      { globalNum: 183, patternNum: 9, title: "Maximum Product Subarray", lcNumber: 152, difficulty: "Medium" },
      { globalNum: 184, patternNum: 10, title: "Word Break", lcNumber: 139, difficulty: "Medium" },
      { globalNum: 185, patternNum: 11, title: "Longest Increasing Subsequence", lcNumber: 300, difficulty: "Medium" },
      { globalNum: 186, patternNum: 12, title: "Partition Equal Subset Sum", lcNumber: 416, difficulty: "Medium" },
      { globalNum: 187, patternNum: 13, title: "Combination Sum IV", lcNumber: 377, difficulty: "Medium" },
      { globalNum: 188, patternNum: 14, title: "Integer Break", lcNumber: 343, difficulty: "Medium" },
      { globalNum: 189, patternNum: 15, title: "Coin Change II", lcNumber: 518, difficulty: "Medium" },
    ],
  },
  {
    id: 16,
    numStr: "16",
    name: "2-D Dynamic Programming",
    count: 13,
    startGlobal: 190,
    endGlobal: 202,
    problems: [
      { globalNum: 190, patternNum: 1, title: "Unique Paths", lcNumber: 62, difficulty: "Medium" },
      { globalNum: 191, patternNum: 2, title: "Longest Common Subsequence", lcNumber: 1143, difficulty: "Medium" },
      { globalNum: 192, patternNum: 3, title: "Best Time to Buy & Sell Stock w/ Cooldown", lcNumber: 309, difficulty: "Medium" },
      { globalNum: 193, patternNum: 4, title: "Coin Change II", lcNumber: 518, difficulty: "Medium" },
      { globalNum: 194, patternNum: 5, title: "Target Sum", lcNumber: 494, difficulty: "Medium" },
      { globalNum: 195, patternNum: 6, title: "Interleaving String", lcNumber: 97, difficulty: "Medium" },
      { globalNum: 196, patternNum: 7, title: "Longest Increasing Path in Matrix", lcNumber: 329, difficulty: "Hard" },
      { globalNum: 197, patternNum: 8, title: "Distinct Subsequences", lcNumber: 115, difficulty: "Hard" },
      { globalNum: 198, patternNum: 9, title: "Edit Distance", lcNumber: 72, difficulty: "Hard" },
      { globalNum: 199, patternNum: 10, title: "Burst Balloons", lcNumber: 312, difficulty: "Hard" },
      { globalNum: 200, patternNum: 11, title: "Regular Expression Matching", lcNumber: 10, difficulty: "Hard" },
      { globalNum: 201, patternNum: 12, title: "Maximal Square", lcNumber: 221, difficulty: "Medium" },
      { globalNum: 202, patternNum: 13, title: "Wildcard Matching", lcNumber: 44, difficulty: "Hard" },
    ],
  },
  {
    id: 17,
    numStr: "17",
    name: "Bit Manipulation",
    count: 8,
    startGlobal: 203,
    endGlobal: 210,
    problems: [
      { globalNum: 203, patternNum: 1, title: "Single Number", lcNumber: 136, difficulty: "Easy" },
      { globalNum: 204, patternNum: 2, title: "Number of 1 Bits", lcNumber: 191, difficulty: "Easy" },
      { globalNum: 205, patternNum: 3, title: "Counting Bits", lcNumber: 338, difficulty: "Easy" },
      { globalNum: 206, patternNum: 4, title: "Reverse Bits", lcNumber: 190, difficulty: "Easy" },
      { globalNum: 207, patternNum: 5, title: "Missing Number", lcNumber: 268, difficulty: "Easy" },
      { globalNum: 208, patternNum: 6, title: "Sum of Two Integers", lcNumber: 371, difficulty: "Medium" },
      { globalNum: 209, patternNum: 7, title: "Reverse Integer", lcNumber: 7, difficulty: "Medium" },
      { globalNum: 210, patternNum: 8, title: "Single Number II", lcNumber: 137, difficulty: "Medium" },
    ],
  },
  {
    id: 18,
    numStr: "18",
    name: "Math & Geometry",
    count: 9,
    startGlobal: 211,
    endGlobal: 219,
    problems: [
      { globalNum: 211, patternNum: 1, title: "Happy Number", lcNumber: 202, difficulty: "Easy" },
      { globalNum: 212, patternNum: 2, title: "Plus One", lcNumber: 66, difficulty: "Easy" },
      { globalNum: 213, patternNum: 3, title: "Pow(x, n)", lcNumber: 50, difficulty: "Medium" },
      { globalNum: 214, patternNum: 4, title: "Multiply Strings", lcNumber: 43, difficulty: "Medium" },
      { globalNum: 215, patternNum: 5, title: "Detect Squares", lcNumber: 2013, difficulty: "Medium" },
      { globalNum: 216, patternNum: 6, title: "Set Matrix Zeroes", lcNumber: 73, difficulty: "Medium" },
      { globalNum: 217, patternNum: 7, title: "Spiral Matrix", lcNumber: 54, difficulty: "Medium" },
      { globalNum: 218, patternNum: 8, title: "Rotate Image", lcNumber: 48, difficulty: "Medium" },
      { globalNum: 219, patternNum: 9, title: "Greatest Common Divisor of Strings", lcNumber: 1071, difficulty: "Easy" },
    ],
  },
  {
    id: 19,
    numStr: "19",
    name: "String Algorithms",
    count: 8,
    startGlobal: 220,
    endGlobal: 227,
    problems: [
      { globalNum: 220, patternNum: 1, title: "Find the Index of the First Occurrence", lcNumber: 28, difficulty: "Easy" },
      { globalNum: 221, patternNum: 2, title: "Repeated Substring Pattern", lcNumber: 459, difficulty: "Easy" },
      { globalNum: 222, patternNum: 3, title: "Longest Happy Prefix (KMP)", lcNumber: 1392, difficulty: "Hard" },
      { globalNum: 223, patternNum: 4, title: "Shortest Palindrome", lcNumber: 214, difficulty: "Hard" },
      { globalNum: 224, patternNum: 5, title: "Rotate String", lcNumber: 796, difficulty: "Easy" },
      { globalNum: 225, patternNum: 6, title: "Rabin-Karp String Match", lcNumber: 187, difficulty: "Medium" },
      { globalNum: 226, patternNum: 7, title: "Manacher's Algorithm (Longest Palindrome)", lcNumber: 5, difficulty: "Hard" },
      { globalNum: 227, patternNum: 8, title: "Distinct Echo Substrings", lcNumber: 1316, difficulty: "Hard" },
    ],
  },
];
